repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: astro-check
        name: astro check
        entry: pnpm astro check
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: astro-build
        name: astro build
        entry: pnpm build
        language: system
        pass_filenames: false
        stages: [pre-push]
